name: ghostwire

x-common: &common
  restart: unless-stopped
  env_file: [.env]
  volumes:
    - ./:/work
    - ./artifacts:/shared
  tty: true
  stdin_open: true

services:
  web:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ${IMAGE_PREFIX:-local}/ghostwire:web
    container_name: ghostwire-web
    environment:
      GHOST_LABEL: web

  net:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.net
    image: ${IMAGE_PREFIX:-local}/ghostwire:net
    container_name: ghostwire-net
    environment:
      GHOST_LABEL: network

  wifi:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.wifi
    image: ${IMAGE_PREFIX:-local}/ghostwire:wifi
    container_name: ghostwire-wifi
    cap_add: ["NET_RAW", "NET_ADMIN"]
    environment:
      GHOST_LABEL: wifi

  mobile:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.mobile
    image: ${IMAGE_PREFIX:-local}/ghostwire:mobile
    container_name: ghostwire-mobile
    environment:
      GHOST_LABEL: mobile

  ad:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.ad
    image: ${IMAGE_PREFIX:-local}/ghostwire:ad
    container_name: ghostwire-ad
    environment:
      GHOST_LABEL: ad
