name: ghostwire

x-common: &common
  restart: unless-stopped
  env_file: [.env]
  volumes:
    - ./:/work
    - ./artifacts:/shared
  tty: true
  stdin_open: true
  environment: &common-env
    SOCKS5_HOST: ${SOCKS5_HOST:-127.0.0.1}
    SOCKS5_PORT: ${SOCKS5_PORT:-1080}
  networks:
    - default
    - vpn

services:
  web:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: ghostwire-web
    environment:
      <<: *common-env
      GHOST_LABEL: web

  net:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.net
    container_name: ghostwire-net
    environment:
      <<: *common-env
      GHOST_LABEL: network

  wifi:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.wifi
    container_name: ghostwire-wifi
    cap_add: ["NET_RAW", "NET_ADMIN"]
    environment:
      <<: *common-env
      GHOST_LABEL: wifi

  mobile:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.mobile
    container_name: ghostwire-mobile
    environment:
      <<: *common-env
      GHOST_LABEL: mobile

  ad:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.ad
    container_name: ghostwire-ad
    environment:
      <<: *common-env
      GHOST_LABEL: ad

networks:
  default:
  vpn:
    external: true
    name: ${VPN_NETWORK:-vpn}

